### PR TITLE
Branch cosmetic updates

### PR DESCRIPTION
**Pull request by yuhaochua**
Edited the code to resolve the issues that are mainly cosmetic in nature, such as wrong error messages.

### CODE REVIEW

**Review by shunyao643 — APPROVED** [review]
LGTM. Just to confirm my understanding, if there is less than 6 attributes to be added, it will fail early on. In `prepareModification`, then the check is done for 6 unique argument tags?

**Comment by shunyao643** [comment]
@Bryan-BC please take a look and merge if you can!

**Comment by yuhaochua** [comment]
> LGTM. Just to confirm my understanding, if there is less than 6 attributes to be added, it will fail early on. In `prepareModification`, then the check is done for 6 unique argument tags?

Almost right, the check for 6 unique argument tags is done with the `checkAttributes` method in AddCommand.

**Comment by Bryan-BC** [comment]
LGTM

**Pull request merged**
